# Generated by Django 2.2.3 on 2019-11-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modifiled_time',
            new_name='modified_time',
        ),
    ]
